config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  get :followers, on: :member
  get :follows, on: :member
  end

  get 'chats/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :groups do
    get 'join' => 'groups#join'
  end

  get "search_book" => "books#search_book"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :image

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to  groups_path
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.file_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Group</h3>
        <%= render 'form', group: @group %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>
        <tr><%= image_tag current_user.get_profile_image, size:'100x100' %></tr>
        <tr>
	        <th>name</th>
	        <th><%= current_user.name %></th>
        </tr>
        <tr>
	        <th>introduction</th>
	        <th><%= current_user.introduction %></th>
        </tr>
      </table>

      <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td>
                <% if group.image.attached? %>
                  <%= image_tag group.image, size: "100x100" %>
                <% else %>
                  <%= image_tag 'no_image', size: "100x100" %>
                <% end %>
              </td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.users.count %></td>
              <td>
                <% if group.owner_id == current_user.id %>
                  <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>
        <tr><%= image_tag current_user.get_profile_image, size:'100x100' %></tr>
        <tr>
	        <th>name</th>
	        <th><%= current_user.name %></th>
        </tr>
        <tr>
	        <th>introduction</th>
	        <th><%= current_user.introduction %></th>
        </tr>
      </table>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th>メンバー</th>
          <th></th>
        </tr>


        <tr>
          <td>
            <% if @group.image.attached? %>
                  <%= image_tag @group.image, size: "100x100" %>
                <% else %>
                  <%= image_tag 'no_image', size: "100x100" %>
                <% end %>
          </td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
              <% @group.users.each do |user| %>
              <%= user.name %><br>
              <% end %>
          </td>
          <td>
            <% if @group.owner_id == current_user.id %>
              <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %>
            <% elsif @group.users.include?(current_user) %>
                <%= link_to 'Leave this group', group_path(@group), method: :delete, class: "btn btn-sm btn-danger" %>
            <% else %>
                <%= link_to 'Join this group', group_join_path(@group), class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>