config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  get :followers, on: :member
  get :follows, on: :member
  end

  get 'chats/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :groups do
    get 'join' => 'groups#join'
  end

  get "search_book" => "books#search_book"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships, foreign_key: :follower_id
  has_many :followers, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id
  has_many :follows, through: :reverse_of_relationships, source: :follower

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end

  def follow(user_id)
  relationships.create(followed_id: user_id)
  end


  def following?(user)
    follows.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def follows
    user = User.find(params[:id])
    @users = user.follows
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.follows.count, follows_user_path(user) %></th>
  </tr>
</table>

<% if user != current_user %>
  <% if user.is_followed_by?(current_user) %>
    <%= link_to user_relationships_path(user), method: :delete, data: {turbolinks: true} do %>
       <button type="button" class="btn btn btn-primary mb-3">フォロー外す</button>
    <% end %>
  <% else %>
    <%=link_to user_relationships_path(user), method: :post do %>
      <button type="button" class="btn btn btn-success mb-3">フォローする</button>
    <% end %>
  <% end %>
<% end %>

<% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
  <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
<% end %>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follows Users</h1>

<% if @users.empty? %>
  <span>ユーザーはいません</span>

<% else %>

<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followers.count %></td>
        <td>フォロワー数:<%= user.follows.count %></td>
        <td>
          <% if user != current_user %>
            <% if user.is_followed_by?(current_user) %>
              <%=link_to "フォロー外す", user_relationships_path(user), method: :delete %>

            <% else %>
              <%=link_to "フォローする", user_relationships_path(user), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/users/follows.html.erb
<h1>Follower Users</h1>

<% if @users.empty? %>
  <span>ユーザーはいません</span>

<% else %>

<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followers.count %></td>
        <td>フォロワー数:<%= user.follows.count %></td>
        <td>
          <% if user != current_user %>
            <% if user.is_followed_by?(current_user) %>
              <%=link_to "フォロー外す", user_relationships_path(user), method: :delete %>

            <% else %>
              <%=link_to "フォローする", user_relationships_path(user), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
     <h2>Users</h2>
     <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
     <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @today_book.count %></td>
              <td><%= @yesterday_book.count %></td>
              <td>
                <% if @yesterday_book.count == 0 %>
                  前日の投稿はありません
                <% else %>
                  <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
                  <%= (@the_day_before * 100).round %>%
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>先週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @this_week_book.count %></td>
            <td><%= @last_week_book.count %></td>
            <td><% if @last_week_book.count == 0 %>
                  先週の投稿はありません
                <% else %>
                  <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
                  <%= (@the_week_before * 100).round %>%
                <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>