config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  get :followers, on: :member
  get :follows, on: :member
  end

  get 'chats/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :groups do
    get 'join' => 'groups#join'
  end

  get "search_book" => "books#search_book"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  scope :latest, -> {order(created_at: :desc)}
  scope :star_count, -> {order(star: :desc)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search(search_word)
    Book.where(['category LIKE ?', "#{search_word}"])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
      unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
        current_user.view_counts.create(book_id: @book.id)
      end
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    @book = Book.new
    @user = current_user

    if params[:latest]
      @books = Book.latest
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search_book
     @book = Book.new
     @books = Book.search(params[:keyword])
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <%= render 'layouts/errors', obj: book %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_area :category, class: 'form-control book_category' %>
  </div>
  <div class ="form-group" id="star">
    <%= f.label :star,'Rate', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :star, id: :review_star %>
　</div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>

  <script>
  $(document).on('turbolinks:load', function() {
　  $('#star').empty();
    $('#star').raty({
      size     : 20,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
   　　scoreName: 'book[star]',
      half: false,
    });
  });
  </script>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td><% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(book), method: :delete do %>
                ♥<%= book.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post do %>
                ♡<%= book.favorites.count %>
              <% end %>
            </p>
            <% end %>
        </td>
        <td>
          <p><%= "コメント数: #{book.book_comments.count}" %></p>
        </td>
        <td>
       <div id="star-rate<%= book.id%>">
          <script>
            $('#star-rate<%= book.id %>').empty();
            $('#star-rate<%= book.id %>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: <%= book.star %>,
            });
          </script>
          </div>
        </td>
        <td>
          <p><%= "閲覧数: #{book.view_counts.count}" %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to '新しい順', books_path(latest: "true") %>
      |<%= link_to '評価の高い順', books_path(star_count: "true") %>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/search_book.html.erb
<table class='table table-hover table-inverse'>

  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td><%= link_to search_book_path(keyword: book.category) do %>
              <%= book.category %>
            <% end %>
        </td>
        <td><% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(book), method: :delete do %>
                ♥<%= book.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post do %>
                ♡<%= book.favorites.count %>
              <% end %>
            </p>
            <% end %>
        </td>
        <td>
          <p><%= "コメント数: #{book.book_comments.count}" %></p>
        </td>
        <td>
        <div id="star-rate<%= book.id%>">
          <script>
            $('#star-rate<%= book.id %>').empty();
            $('#star-rate<%= book.id %>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: '<%= book.star %>',
            });
          </script>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= link_to @book.category, @book %></td>
          <td><% if @book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                ♥<%= @book.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(@book), method: :post do %>
                ♡<%= @book.favorites.count %>
              <% end %>
            </p>
            <% end %>
          </td>
          <td>
            <p><%= "コメント数: #{@book.book_comments.count}" %></p>
          </td>
          <td>
            <div id="star-rate<%= @book.id%>"></td>
             <script>
              $('#star-rate<%= @book.id %>').empty();
              $('#star-rate<%= @book.id%>').raty({
                 size      : 20,
                 starOff   : '<%= asset_path('star-off.png') %>',
                 starOn    : '<%= asset_path('star-on.png') %>',
                 half      : false,
                 readOnly: true,
                 score: <%= @book.star %>,
               });
             </script>
          </td>
          <td>
            <p><%= "閲覧数: #{@book.view_counts.count}" %></p>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>

      <table class='table'>

        <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td><%= link_to(@book.user) do %>
              <p><%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
                 <%= book_comment.user.name %>
                <% end %>
              </p>
            </td>
            <td><%= book_comment.comment %></td>
            <td>
              <% if book_comment.user == current_user %>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,  class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>

        <div class="book_comment">
          <%= form_with model: [@book, @book_comment] do |f| %>
            <%= f.text_area :comment, size: "80x5" %><br>
            <%= f.submit "送信" %>
          <% end %>
        </div>

    </div>
  </div>
</div>